### ISSUE TITLE
Can't compile with phoenix 1.5.3, elixir 1.10.3

### ISSUE THREAD

**Issue by deemytch** [slime-lang/phoenix_slime#84]
In plain new project just created

I added  into mix.exs
```{:phoenix_slime, "~> 0.13.1"}```

then 
```
mix do deps.get, compile
Resolving Hex dependencies...
Dependency resolution completed:
...skip...
==> slime
Compiling 1 file (.erl)
Compiling 11 files (.ex)
warning: :slime_parser.parse/1 is undefined (module :slime_parser is not available or is yet to be defined)
  lib/slime/parser.ex:12: Slime.Parser.parse/1
...skip...
== Compilation error in file lib/magazin_web/views/layout_view.ex ==
** (UndefinedFunctionError) function :slime_parser.parse/1 is undefined (module :slime_parser is not available)
    :slime_parser.parse(<<100, 111, 99, 116, 121, 112, 101, 32, 104, 116, 109, 108, 10, 104, 116, 109, 108, 32, 108, 97, 110, 103, 61, 34, 101, 110, 34, 10, 14, 32, 32, 104, 101, 97, 100, 10, 14, 32, 32, 32, 32, 109, 101, 116, 97, 32, 99, 104, 97, 114, ...>>)
    lib/slime/parser.ex:12: Slime.Parser.parse/1
    lib/slime/renderer.ex:17: Slime.Renderer.precompile/1
    lib/phoenix_slime/engine.ex:9: PhoenixSlime.Engine.compile/2
    (phoenix 1.5.3) lib/phoenix/template.ex:351: Phoenix.Template.compile/3
    (phoenix 1.5.3) lib/phoenix/template.ex:166: anonymous fn/4 in Phoenix.Template."MACRO-__before_compile__"/2
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix 1.5.3) expanding macro: Phoenix.Template.__before_compile__/1
    lib/magazin_web/views/layout_view.ex:1: MagazinWeb.LayoutView (module)
    (elixir 1.10.3) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

Erlang/OTP 22 [erts-10.7.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.10.3 (compiled with Erlang/OTP 22)
